var sourcesIndex = JSON.parse('{\
"bytecount":["",[],["integer_simd.rs","lib.rs","naive.rs"]],\
"byteorder":["",[],["io.rs","lib.rs"]],\
"magnus":["",[["value",[],["flonum.rs"]]],["binding.rs","block.rs","class.rs","encoding.rs","enumerator.rs","error.rs","exception.rs","float.rs","gc.rs","integer.rs","into_value.rs","lib.rs","macros.rs","method.rs","module.rs","numeric.rs","object.rs","r_array.rs","r_bignum.rs","r_complex.rs","r_file.rs","r_float.rs","r_hash.rs","r_match.rs","r_object.rs","r_rational.rs","r_regexp.rs","r_string.rs","r_struct.rs","r_typed_data.rs","range.rs","ruby_handle.rs","scan_args.rs","symbol.rs","try_convert.rs","typed_data.rs","value.rs"]],\
"magnus_macros":["",[],["init.rs","lib.rs","typed_data.rs","util.rs"]],\
"memchr":["",[["memchr",[],["fallback.rs","iter.rs","mod.rs","naive.rs"]],["memmem",[["prefilter",[],["fallback.rs","mod.rs"]]],["byte_frequencies.rs","mod.rs","rabinkarp.rs","rarebytes.rs","twoway.rs","util.rs"]]],["cow.rs","lib.rs"]],\
"minimal_lexical":["",[],["bigint.rs","extended_float.rs","lemire.rs","lib.rs","mask.rs","num.rs","number.rs","parse.rs","rounding.rs","slow.rs","stackvec.rs","table.rs","table_lemire.rs","table_small.rs"]],\
"nom":["",[["bits",[],["complete.rs","mod.rs","streaming.rs"]],["branch",[],["mod.rs"]],["bytes",[],["complete.rs","mod.rs","streaming.rs"]],["character",[],["complete.rs","mod.rs","streaming.rs"]],["combinator",[],["mod.rs"]],["multi",[],["mod.rs"]],["number",[],["complete.rs","mod.rs","streaming.rs"]],["sequence",[],["mod.rs"]]],["error.rs","internal.rs","lib.rs","macros.rs","str.rs","traits.rs"]],\
"nom_locate":["",[],["lib.rs"]],\
"nom_tracable":["",[],["lib.rs"]],\
"nom_tracable_macros":["",[],["lib.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"rb_sys":["",[],["bindings.rs","lib.rs","ruby_abi_version.rs","special_consts.rs","value_type.rs"]],\
"serde":["",[["de",[],["format.rs","ignored_any.rs","impls.rs","mod.rs","seed.rs","utf8.rs","value.rs"]],["private",[],["de.rs","doc.rs","mod.rs","ser.rs","size_hint.rs"]],["ser",[],["fmt.rs","impls.rs","impossible.rs","mod.rs"]]],["integer128.rs","lib.rs","macros.rs"]],\
"serde_derive":["",[["internals",[],["ast.rs","attr.rs","case.rs","check.rs","ctxt.rs","mod.rs","receiver.rs","respan.rs","symbol.rs"]]],["bound.rs","de.rs","dummy.rs","fragment.rs","lib.rs","pretend.rs","ser.rs","this.rs","try.rs"]],\
"syn":["",[["gen",[],["clone.rs","debug.rs","eq.rs","fold.rs","gen_helper.rs","hash.rs"]]],["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","drops.rs","error.rs","export.rs","expr.rs","ext.rs","file.rs","generics.rs","group.rs","ident.rs","item.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","pat.rs","path.rs","print.rs","punctuated.rs","reserved.rs","sealed.rs","span.rs","spanned.rs","stmt.rs","thread.rs","token.rs","tt.rs","ty.rs","verbatim.rs","whitespace.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"vault":["",[["data",[["chunks",[],["chunk.rs","data_data_chunk.rs","data_sdsc_chunk.rs","fold_chunk.rs","header.rs","mod.rs","trash_data_chunk.rs"]],["ticks",[],["command_tick.rs","message.rs","message_tick.rs","mod.rs","tick.rs"]]],["chunky.rs","header.rs","item.rs","mod.rs","parser.rs","player.rs","replay.rs"]]],["errors.rs","lib.rs","map.rs","message.rs","player.rs","replay.rs"]]\
}');
createSourceSidebar();
