use std::mem;

#[derive(Copy, Clone)]
#[allow(non_camel_case_types)]
#[repr(u8)]
pub enum CommandType {
    //[EntityCommandType]
    CMD_DefaultAction = 0,
    CMD_Stop = 1,
    CMD_Destroy = 2,
    CMD_BuildSquad = 3,
    CMD_InstantBuildSquad = 4,
    CMD_CancelProduction = 5,
    CMD_BuildStructure = 6,
    CMD_Move = 7,
    CMD_FlightMove = 8,
    CMD_Face = 9,
    CMD_Attack = 10,
    CMD_AttackMove = 11,
    CMD_RallyPoint = 12,
    CMD_Capture = 13,
    CMD_Ability = 14,
    CMD_Evacuate = 15,
    CMD_Upgrade = 16,
    CMD_InstantUpgrade = 17,
    CMD_Load = 18,
    CMD_Unload = 19,
    CMD_UnloadSquads = 20,
    CMD_AttackStop = 21,
    CMD_AttackForced = 22,
    CMD_SetHoldHeading = 23,
    CMD_StopMove = 24,
    CMD_Paradrop = 25,
    CMD_DefuseMine = 26,
    CMD_Casualty = 27,
    CMD_Death = 28,
    CMD_InstantDeath = 29,
    CMD_Projectile = 30,
    CMD_PlaceCharge = 31,
    CMD_BuildEntity = 32,
    CMD_RescueCasualty = 33,
    CMD_AttackFromHold = 34,
    CMD_Vault = 35,
    CMD_KnockedBack = 36,
    CMD_Teardown = 37,
    CMD_Melee = 38,
    CMD_ResolveOverlap = 39,
    CMD_Stun = 40,
    CMD_InstantSetupTeamWeapon = 41,
    CMD_SetupTeamWeapon = 42,
    CMD_MoveToCover = 43,
    CMD_Taunted = 44,
    CMD_Trade = 45,
    CMD_Brace = 46,
    CMD_Gather = 47,
    CMD_PickUpSimItem = 48,
    CMD_ChangeCombatSlot = 49,
    CMD_RetreatMove = 50,
    CMD_StopAbility = 51,
    CMD_InstantLoad = 52,
    CMD_RestoreWreck = 53,
    CMD_Disable = 54,
    CMD_Enable = 55,
    CMD_CancelConstruction = 56,
    CMD_HoldPositionOn = 57,
    CMD_HoldPositionOff = 58,
    CMD_CancelRestoreWreck = 59,
    CMD_Repair = 60,
    CMD_COUNT = 61,

    //[SquadCommandType]
    SCMD_Move = 62,
    SCMD_Stop = 63,
    SCMD_Destroy = 64,
    SCMD_BuildStructure = 65,
    SCMD_Capture = 66,
    SCMD_Attack = 67,
    SCMD_ReinforceUnit = 68,
    SCMD_Upgrade = 69,
    SCMD_CancelProduction = 70,
    SCMD_AttackMove = 71,
    SCMD_Ability = 72,
    SCMD_Load = 73,
    SCMD_InstantLoad = 74,
    SCMD_UnloadSquads = 75,
    SCMD_Unload = 76,
    SCMD_PickupTrailer_UNUSED = 77,
    SCMD_Retreat = 78,
    SCMD_CaptureTeamWeapon = 79,
    SCMD_SetMoveType = 80,
    SCMD_InstantReinforceUnit = 81,
    SCMD_InstantUpgrade = 82,
    SCMD_PlaceCharge = 83,
    SCMD_DefuseCharge = 84,
    SCMD_DropTrailer_UNUSED = 85,
    SCMD_PickUpSimItem = 86,
    SCMD_DefuseMine = 87,
    SCMD_DoPlan = 88,
    SCMD_Patrol = 89,
    SCMD_Surprise = 90,
    SCMD_InstantSetupTeamWeapon = 91,
    SCMD_SetupTeamWeapon = 92,
    SCMD_AbandonTeamWeapon = 93,
    SCMD_StationaryAttack = 94,
    SCMD_RevertFieldSupport = 95,
    SCMD_Face = 96,
    SCMD_BuildSquad = 97,
    SCMD_RallyPoint = 98,
    SCMD_RescueCasualty = 99,
    SCMD_Recrew = 100,
    SCMD_Merge = 101,
    SCMD_WeaponPreference = 102,
    SCMD_CombatStance = 103,
    SCMD_MoveToCover = 104,
    SCMD_Gather = 105,
    SCMD_AttackWithinLeashArea = 106,
    SCMD_JoinFormationSquadGroup = 107,
    SCMD_Trade = 108,
    SCMD_HoldPosition = 109,
    SCMD_Evacuate = 110,
    SCMD_Vault = 111,
    SCMD_CancelQueuedCommand = 112,
    SCMD_RespondToBeingBreached = 113,
    SCMD_StopAbility = 114,
    SCMD_InstantParadropReinforceUnit = 115,
    SCMD_MoveUntilInsidePlayableArea = 116,
    SCMD_BeingTowed = 117,
    SCMD_AttachingTrailer = 118,
    SCMD_DetachingTrailer_UNUSED = 119,
    SCMD_RestoreWreck_UNUSED = 120,
    SCMD_AnimatedSpawn = 121,
    SCMD_COUNT = 122,

    //[FormationSquadGroupCommandType]
    FCMD_FormationSquadGroupMove = 123,
    FCMD_FormationSquadGroupAttack = 124,
    FCMD_FormationSquadGroupAttackMove = 125,
    FCMD_FormationSquadGroupStop = 126,
    FCMD_COUNT = 127,

    //[PlayerCommandType]
    PCMD_PlaceAndConstructEntities = 128,
    PCMD_ResourceDonation = 129,
    PCMD_CheatResources = 130,
    PCMD_CheatRevealAll = 131,
    PCMD_Ability = 132,
    PCMD_CheatBuildTime = 133,
    PCMD_CheatIgnoreCosts = 134,
    PCMD_Upgrade = 135,
    PCMD_InstantUpgrade = 136,
    PCMD_TentativeUpgrade = 137,
    PCMD_TentativeUpgradePurchaseAll = 138,
    PCMD_UpgradeRemove = 139,
    PCMD_TentativeUpgradeRemoveAll = 140,
    PCMD_SlotItemRemove_DEPRECATED = 141,
    PCMD_CancelProduction = 142,
    PCMD_DetonateCharges = 143,
    PCMD_AIPlayer = 144,
    PCMD_AIPlayer_EncounterNotification = 145,
    PCMD_Surrender = 146,
    PCMD_WaitObjectDone = 147,
    PCMD_BroadcastMessage = 148,
    PCMD_AIPlayer_EncounterSniped = 149,
    PCMD_AIPlayer_ResourceBonus = 150,
    PCMD_FormationSquadGroupCreateBegin = 151,
    PCMD_FormationSquadGroupAddSquad = 152,
    PCMD_FormationSquadGroupCreateEnd = 153,
    PCMD_EndTurn = 154,
    PCMD_StopAbility = 155,
    PCMD_COUNT = 156,

    //[DataCommandType]
    DCMD_CameraTrack = 157,
    DCMD_COUNT = 158,

    Unknown(u8),
}

impl CommandType {

    /// Converts a numerical representation of a `CommandType` enum into the correct enum value by
    /// unsafely transmuting the numerical representation into the `CommandType` type.

    pub fn from_u8(n: u8) -> CommandType {
        if n > 158 {
            CommandType::Unknown(n)
        } else {
            unsafe { mem::transmute(n as u16) }
        }
    }
}
